[project]
name = "opnsense-qbit-sync"
version = "2025.4.1"
description = "Tool to sync an OPNSense Alias to qBittorrent"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
]
